language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO="Django>=1.5,Django<=1.5.99"
  - DJANGO="Django>=1.6,Django<=1.6.99"
  - DJANGO="Django>=1.7,Django<=1.7.99"

install:
  - pip install $DJANGO --use-mirrors

script:
  - python runtests.py

