language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO="Django==1.4.16"
  - DJANGO="Django==1.5.11"
  - DJANGO="Django==1.6.8"
  - DJANGO="Django==1.7.1"

install:
  - pip install $DJANGO --use-mirrors

script:
  - python runtests.py

matrix:
  - exclude:
    - env: DJANGO="Django==1.4.16"
      python: 3.3
    - env: DJANGO="Django==1.4.16"
      python: 3.4
