language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=Django==1.4
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7

install:
  - pip install $DJANGO --use-mirrors

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO=Django==1.4
      python: "3.3"
    - env: DJANGO=Django==1.4
      python: "3.4"

