language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django<1.5"
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"

install:
  - pip install $DJANGO --use-mirrors

script:
  - python runtests.py

before_script:
  - if [[ $DJANGO == 'Django<1.5' ]]; then pip install django-discover-runner; fi

matrix:
  exclude:
  - env: DJANGO="Django<1.5"
    python: "3.3"
  - env: DJANGO="Django<1.5"
    python: "3.4"
  - env: DJANGO="Django<1.5"
    python: "pypy3"
  - env: DJANGO="Django<1.10"
    python: "3.3"
  - env: DJANGO="Django<1.10"
    python: "pypy3"
